# Generated by Django 5.0.1 on 2024-01-08 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_batch_times'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch_times',
            name='end_date',
            field=models.TimeField(unique=True),
        ),
        migrations.AlterField(
            model_name='batch_times',
            name='start_time',
            field=models.TimeField(unique=True),
        ),
    ]
