# Generated by Django 5.0.1 on 2024-01-08 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_batch_times_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch_times',
            name='end_date',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='batch_times',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
