# Generated by Django 5.0.1 on 2024-01-08 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_batch_times_end_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='batch_times',
            old_name='end_date',
            new_name='end_time',
        ),
    ]
