# Generated by Django 5.0.1 on 2024-01-08 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_end_date_batch_times_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='timings',
            field=models.JSONField(null=True),
        ),
    ]
