# Generated by Django 5.0.1 on 2024-01-08 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_course_timings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='timings',
        ),
        migrations.CreateModel(
            name='YourModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('time', models.ManyToManyField(to='app.course')),
            ],
        ),
    ]
